### ISSUE TITLE
classList not working

### ISSUE THREAD

**Issue by pfortes** [eorroe/NodeList.js#10]
using classList and its methods add / remove is not working when selecting with nodeList

```
document.getElementById('id').classList.add('bounceOutLeft', 'hidden')
```
works but using nodeList:
```
$$('#id').classList.add('bounceOutLeft', 'hidden');
```
throws the error: Uncaught TypeError: $$(...).classList.add is not a function(…)

**Comment by eorroe** [comment]
This library does not grab every property/method of everything that gets mapped. So instead use:

I thought it'd be a waste to make a method for whatever that is mapped "classList", and have that loop and call with the arguments, I rather make one method `call` that handles all cases

```
$$('#id').classList.call('add', 'bounceOutLeft', 'hidden');
```

**Comment by eorroe** [comment]
BTW are you planning on using this in production? I have a lot of stars but I don't know how many people are actually using this in production? or even how many have played with this?

**Comment by pfortes** [comment]
Your call method works like a charm, 

And yes, I am planning to use this in production for some tablet web apps.

Thanks
