### ISSUE TITLE
[Question] How works that kind of chaining?

### ISSUE THREAD

**Issue by pwFoo** [eorroe/NodeList.js#12]
Hi,
found your nodelist.js and really like it.
Looked into the code and would happy to understand how you created that kind of chaining?
```
$$('.child').id; // ['', '' ... x10]
```

`$$('.child')` is a list of nodes (nodelist object) and the chained call `.id` not exists in your code. So chained calls (properties / methods?) to nodelist mapped to each item of nodelist?

May you explain how that is done? 🥇

**Comment by eorroe** [comment]
If I'm not mistaken that is done from line [153-157](https://github.com/eorroe/NodeList.js/blob/a9d98bdb69d16b6cf8c6fb7c848103d422ab144e/NodeList.js#L153)

**Comment by pwFoo** [comment]
Hi @eorroe,

thanks for the hint. Isn't that easy to read for me... 
I'm still at the beginning with Javascript :)

nodelist ist really nice! Haven't used it, but like the way it works with nodelists!
Found another way to do that. I used a Proxy to watch and supervise / redirect / loop requests to properties and functions.
I built a small library around querySelectorAll, DOM Ready check, event handling (plan to replace it with event delegation) and map node properties and methods to nodelist with minified 547 bytes (gzipped: 327 bytes).

**Comment by eorroe** [comment]
Lol now you confused me, but good look with that let me know how it goes

**Comment by pwFoo** [comment]
Hi, I created a gist with my small jQuery like class which maps Nodelist to Node methods / attributes via JS proxy.
It included a simple router, event delegation  and tasks (pubsub with prio / sort).

Because I'm new with JS it needs some / much work to improve and cleanup... But simple tests works fine. Minimal demo index.html file included (without router or pubsub...). Also would be nice to move router to a plugin / addon and maybe split tasks (pubsub) feature from event delegation. 

https://gist.github.com/pwFoo/bdd1d0cc38b7575b6ec7121e19499914

The mapping to node features is done by proxyHandler: https://gist.github.com/pwFoo/bdd1d0cc38b7575b6ec7121e19499914#file-jq-js-L94

I know it's not ready to use... but would like to know what you think about?

The minified code (2482 bytes, saved 84.80%)
