### ISSUE TITLE
JSPerf Example

### ISSUE THREAD

**Issue by gwicksted** [eorroe/NodeList.js#4]
How much faster than JQuery for a common use case?

About 3x:

http://jsperf.com/nodelist-vs-jquery

**Comment by eorroe** [comment]
Thanks for the JSperf, but its wrong, NodeListJS, returns an Array for every property mapped, you'll have to do:

``` JS
$$('.menu-item').classList.call('add', 'menu');
$$('.hover').classList.call('add', 'tooltip');
```

It'll loop through all the `classList` objects and call the method `add()`

The case you have would work for `Elements` without any class at all, because their Arrays (So I don't recommend doing)

It's doing:

``` JS
$$('.menu-item').className += ' menu';
```

``` JS
['menu-item'] += ' menu';
```

I'm sure my library will be faster since its not doing what jQuery's doing which is checking what exist, if something doesn't then it'll do it another way. jQuery's purpose was to solve cross browser issues, so it's pretty different, but mine is to not have to do all that since browser APIs are now more in sync.

So I'm not really sure if a jsperf test is necessary, but I guess people would still want to see it :) but please make the change above.

**Comment by eorroe** [comment]
Also make sure to rename to NodeListJS not NodeList the browser has a native NodeList (therefore most will be confused)

Don't say the word **selectors**

> Compare performance of JQuery selectors vs NodeList selectors

Since I'm using the browser's native `document.querySelectorAll` so is jQuery if the browser supports it. Also that's not what you're comparing if you don't want to be super specific to adding classes, just say

> Compare performance of JQuery vs NodeListJS

**Comment by gwicksted** [comment]
Ah I see!  Yes, my initial intent was just to search but I changed it last minute to add classes. Oops. I'll make the aforementioned changes soon and post back here.  I realize it's not meant to be an alternative to jQuery - just thought people would want to know the difference.

**Comment by eorroe** [comment]
Well it could be considered an alternative to javascaript if you don't need to solve browser inconsistencies i.e `attatchEvent` to `addEventListener`

I always used things that are supported in major browsers, if I ever have to support things like above I'd easily do:

```
$$.NL.on = $$.NL.addEventListener ? $$.NL.addEventListener : $$.NL.attatchEvent;
```

But I don't develop for IE, it needs to DIE!

**Comment by gwicksted** [comment]
Well... I spent quite some time with JSPerf and it kept making me perform an image captcha then a text captcha then would either return to the edit screen (reverting all my changes) or save (usually after I missed re-doing something such as the public checkbox)...  =/

I did get an error testing `.classList.call` with JSPerf ... but who knows what was going on.  If you have better luck - please perform the edits.

I also noticed my original HTML was missing a `</p>`.

**Comment by eorroe** [comment]
lol, `classList` not `className`

`$$('.menu-item').classList` returns an Array of [these](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList)

then `call()` will call the passed method and arguments on each `classList`

**Comment by gwicksted** [comment]
Yeah - I tried classList (probably wasn't the last saved edit).  This was the code (it might be in the JSPerf revision history -- not sure if that edit went public or not):

``` javascript
$$('.menu-item').classList.call('add', 'menu');
$$('.hover').classList.call('add', 'tooltip');
```

**Comment by eorroe** [comment]
What browser you on?

and no looking at the last revision it shows your using `className`:

``` JS
$$('.menu-item').className.call('add', 'menu');
$$('.hover').className.call('add', 'tooltip');
```

Which `add` is not a method of `String`

**Comment by gwicksted** [comment]
Chrome - their Browserscope reports it as `Chrome 45.0.2454` - haven't tried any other browsers yet.

**Comment by eorroe** [comment]
Then [it'll work](http://caniuse.com/#search=classlist) but your code is using `className` instead of `classList`

**Comment by gwicksted** [comment]
``` text
Testing in Chrome 45.0.2454.101 32-bit on Windows NT 10.0 64-bit
Test    Ops/sec
```

# jQuery

``` javascript
$('.menu-item').addClass('menu');
$('.hover').addClass('tooltip');
```

``` text
129,082
±0.55%
fastest
```

# NodeListJS

``` javascript
$$('.menu-item').classList.call('add', 'menu');
$$('.hover').classList.call('add', 'tooltip');
```

``` text
ERROR
TypeError: Cannot read property 'call' of undefined.

Uncaught TypeError: Cannot read property 'name' of undefined.

message: Uncaught TypeError: Cannot read property 'name' of undefined
fileName: http://jsperf.com/benchmark-47.js
lineNumber: 21
```

**Comment by gwicksted** [comment]
See [this version](http://jsperf.com/nodelist-vs-jquery/5)

**Comment by eorroe** [comment]
Just saw the update now, not sure why that's happening. `call()` on NodeLists skips any `undefined` or `null`.

I'm looking at that version

I get:

```
TypeError: Cannot read property 'call' of undefined.

Uncaught TypeError: Cannot read property 'name' of undefined.
```

The `benchmark-47.js` file is unreadable, so the line number doesn't help

**Comment by gwicksted** [comment]
I know - something funny is going on.  I'm installing Python27 on this box, grabbing benchmark.js (what they use under the hood) then I'll set up an express server and see what happens!

**Comment by eorroe** [comment]
Seems to be a jsperf problem

when you debug it, its doing:

``` JS
(R = T.createElement(U)).name = S;
```

`T.createElement(U)` returns a div and then it trys to get the property `name` which is undefiend

**UPDATE:**

```
T = frames[P("iframe", W.container)[0].name].document
```

That's where `name` is undefined

**Comment by gwicksted** [comment]
And the plot thickens... I can confirm it's a jsperf and not benchmark.js problem.  Also, when running in my browser, I get the following results:

``` text
NodeListJS x 123,589 ops/sec ±2.97% (89 runs sampled)
bench.js:17 jQuery x 136,521 ops/sec ±1.65% (97 runs sampled)
bench.js:20 Fastest is jQuery
```

It may not be resetting between runs and it's not sampling thousands of times yet.  Just thought I'd keep you updated.  However, I'm done for the night.  Take care.

**Comment by eorroe** [comment]
Thanks, good night.

**Comment by gwicksted** [comment]
[Someone else](https://github.com/jsperf/jsperf.com/issues/45) had this happen to them.

**Comment by eorroe** [comment]
Okay so I thought it may had to do something with rawgit, looks like its not, I made another test case, so whenever your going to do an edit, click edit from revision 5 not 6

**Comment by ghost** [comment]
There is a bug in the code by firefox:

> TypeError: P(...)[0] is undefined.
> 
> message: TypeError: P(...)[0] is undefined
>  fileName: http://jsperf.com/benchmark-47.js
>  lineNumber: 21

**Comment by eorroe** [comment]
@inf3rno It's a jsperf bug, not my library
